### PR TITLE
Fix date issue on work order notes

### PR DESCRIPTION
**Pull request by LBHCallumM**
### Description of change

The closedDate property from getWorkOrder endpoint is actually spelled `closedDated`. 

This caused the date to be missing from the note.

### CODE REVIEW

**Review by Duslerke — COMMENTED** [review]
Why not fix the spelling mistake in the source instead?

**Comment by LBHCallumM** [comment]
> Why not fix the spelling mistake in the source? _(instead of propagating it into a wider codebase)_
> 
> Seems like it would be a more wholesome fix.

where

**Comment by LBHCallumM** [comment]
> Why not fix the spelling mistake in the source? _(instead of propagating it into a wider codebase)_
> 
> Seems like it would be a more wholesome fix.

Making a small change, vs two prs and extensive changes accross the frontend? hmmm

**Comment by Duslerke** [comment]
> > Why not fix the spelling mistake in the source? _(instead of propagating it into a wider codebase)_
> > Seems like it would be a more wholesome fix.
> 
> Making a small change, vs two prs and extensive changes accross the frontend? hmmm

For where: wherever the data is coming from (if reasonable)
2 PRs: It will make the overall code cleaner for everyone, plus this will remove the ambiguity as to what this key actually means now. It's unclear whether it's meant to mean: "closed date" or "close dated". :grin:

**Review by adamtry — APPROVED** [review]

**Pull request merged**
